
#port
server:
  port: 80
  
#mysql
spring:
  database:
    url: jdbc:mysql://localhost:3306/mydb?autoReconnection=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        storage_engine: innodb
    logging: 
      level: 
        org: 
          hibernate: info
        hibernate: 
          show_sql: true
          format_sql: true
          user_sql_comments: true
          
  #jsp/thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML