#YAML 형식

#port
server:
  port: 80

spring:
  #database
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: hr
    password: happy
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
  #thymeleaf
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false

#mybatis
mybatis:
  Config: config.xml
  type-aliases-package: com.sist.web.vo
  mapper-locations: classpath:mapper/**/*.xml